# Generated by Django 5.0 on 2023-12-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('CIK', models.CharField(max_length=10, unique=True)),
                ('SIC', models.CharField(blank=True, max_length=4, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('IRS_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=10)),
                ('date_filed', models.DateTimeField()),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('filing_url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='FilingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stockApp.filing')),
            ],
        ),
    ]
