# Generated by Django 5.0 on 2023-12-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='filing',
            name='company',
        ),
        migrations.RemoveField(
            model_name='filingcontent',
            name='filing',
        ),
        migrations.DeleteModel(
            name='InvestorEducation',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Filing',
        ),
        migrations.DeleteModel(
            name='FilingContent',
        ),
    ]
