# Generated by Django 5.0 on 2024-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_stock_remove_filing_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik_number', models.BigIntegerField(unique=True)),
                ('ticker_symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
