# Generated by Django 5.0 on 2024-01-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_rename_cik_number_stock_info_cik_str_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=10)),
                ('filing_date', models.DateField()),
                ('document_url', models.URLField()),
                ('accession_number', models.CharField(max_length=20, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.stock_info')),
            ],
        ),
    ]
